### ISSUE TITLE
API.addSettings('skin', 'demo') does not work well in version 0.1

### ISSUE THREAD

**Issue by baranan** [minnojs/minno-quest#149]
I use API.addSettings('skin', 'demo'); to set the correct style for the questionnaires. In 0.0, it shows the correct style:
![image](https://cloud.githubusercontent.com/assets/4257111/21742296/404c41c6-d4f4-11e6-91b7-01345d08d567.png)

In 0.1: 
![image](https://cloud.githubusercontent.com/assets/4257111/21742303/6ae09fae-d4f4-11e6-94cc-144122f501a1.png)

So, the 'demo' skin doesn't seem to apply the correct style in version 0.1.

**Comment by eladzlot** [comment]
As far as I can recall, we decided that the demo style should be the default in v0.1
So you shouldn't be adding any skins at all.
