### ISSUE TITLE
The demo skin in manager 0.1

### ISSUE THREAD

**Issue by baranan** [minnojs/minno-quest#151]
When I use API.addSettings('skin','demo'); in my manager file, I get the wrong buttons layout:
![image](https://cloud.githubusercontent.com/assets/4257111/25060790/7a514e78-21ae-11e7-9a29-a31597c092a1.png)

When I comment out that line, I get the correct buttons:
![image](https://cloud.githubusercontent.com/assets/4257111/25060798/ad50c344-21ae-11e7-84c9-8df67a20a2d9.png)

I am using manager 0.1. I understand that the default skin is 'demo' so I don't need to use it in the manager, but why would using it change the style? It doesn't seem like the correct behavior.

I found this with this study:
https://app-prod-03.implicit.harvard.edu/implicit/showfiles.jsp?user=yba&study=relmem1
With this questionnaire:
https://app-prod-03.implicit.harvard.edu/implicit/user/yba/relmem1/mem.js
But, the study is complex, and I removed the comment, so I'm not sure these files will help you debug the issue.

**Comment by eladzlot** [comment]
It is not called the "demo" skin anymore, it is simply called "default".
That made most sense to me. Can be changed if you like...

**Comment by baranan** [comment]
But why should using that code [API.addSettings('skin','demo');] create a different style? Is it an actual style that is presented as designed?  That is confusing if 'demo' means one skin in version 0.0 and another skin in version 0.1.  We can assume that many researchers would still have that line in their code, with the intention of showing the style that is shown by default in the current version.

**Comment by eladzlot** [comment]
This change is the reason that we changed versions between 0.0 and 0.1
We wanted to remove the demo skin because it doesn't make sense in a
general context (as opposed to our system). It shouldn't be difficult to
put it back in as a synonym to default.

**Comment by baranan** [comment]
1. The serious problem is that is **has** an effect on the style, but not the expected effect.
2. It should simply do nothing or be a synonym of default (because it is the default).

**Comment by andrewdzik** [comment]
So currently if you do something like API.addSettings('skin','test123');
then it will have the same behavior?  What do we want to happen when you
try to load a skin that does not exist?

**Comment by baranan** [comment]
The skin should not change from the default skin if someone requests a skin that does not exist. If I understand correctly, that was the bug I reported at the top of this thread. 

As for how to notify to the user that the skin does not exist, I think you can use a comment in the console that is also shown at bottom of the screen in the development server (as you do with other messages, like when a task is refreshed and you notify that a task has been saved twice).

**Comment by eladzlot** [comment]
For now, I simply added a demo skin that is identical to default.
It's the simplest way to avoid this problem...
